[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "religion_in_congress"
version = "0.1.0"
authors = [{name = "Lavinia Dunagan", email = "laviniad@umich.edu"}]
